Second refactor
Split functionality into 2 other scripts.
Removed deprecated code. Operation syntax change.

Signed-off-by: GaKu999 <gaku999@posteo.net>

diff --git a/vconsole-colors b/vconsole-colors
--- a/vconsole-colors
+++ b/vconsole-colors
@@ -1,171 +1,102 @@
-#!/bin/sh
-# vim:ft=sh:noet:ts=3:sw=3:
+#!/usr/bin/env bash
+# vim:ft=bash:noet:ts=3:sw=3:
 
-if [ -n "$DEBUG" ] ; then
+if [[ -n "$DEBUG" ]] ; then
 	set -x
 fi
 
 # Who am I?
 _SELF="${0##*/}"
 
-# used by _parse()
-_ENV_FILE="@ENV_FILE@"
-
-# stdin: heredoc text
-_herecat() {
-	local msg line lfcr
-	lfcr="$(printf '%b' "\012\015")"
-	while IFS="$lfcr" read -r line ; do
-		msg="$msg$line$lfcr"
-	done
-	printf '%s' "$msg"
-}
-
 # [$1: EXIT CODE (0)]
-_usage() { local ec="${1:-0}"
-	_herecat << ENDUSAGETEXT
-Usage: $_SELF [ARG...] [OPERATION]
+function _usage { local ec="${1:-0}"
+	local msg
+	IFS='' read -r -d '' msg << ENDUSAGEMSG
+Usage: $_SELF [-C CONSOLE] [-E FILE] [MODE]
 
-  OPERATIONS:
-   get*
-   parse
-   set [CONSOLE]
+  MODES:
+   get*       get the configured and current colors
+   set        set the colors
 
-  -E --env-file FILE
+  -C CONSOLE  console to use
+  -E FILE     environment file
 
-  -h --help
-  --usage
-ENDUSAGETEXT
+  -h          display this help and exit
+ENDUSAGEMSG
+	printf '%s' "$msg"
 	exit "$ec"
 }
 
-#==============================================================================#
-# DEPRECATED/REWRITE
-
-## $1: base16 value
-_hex2dec() {
-	local __hex_value="$1"
-	printf "%d" "0x$__hex_value"
-}
-
-## $1: base10 value
-_dec2hex() {
-	local __dec_value="$1"
-	printf "%.2x" "$__dec_value"
-}
-
-## get the current color variables
-_get() {
-	local __i __c
-	local __c0 __c1 __c2 __c3 __c4 __c5 __c6 __c7 __c8 __c9 __c10 __c11 __c12 __c13 __c14 __c15 # read values
-	local __cl0 __cl1 __cl2 __cl3 __cl4 __cl5 __cl6 __cl7 __cl8 __cl9 __cl10 __cl11 __cl12 __cl13 __cl14 __cl15 # processed values
-
-	for __c in "red" "grn" "blu"
-	do
-		IFS=',' read -r __c0 __c1 __c2 __c3 __c4 __c5 __c6 __c7 __c8 __c9 __c10 __c11 __c12 __c13 __c14 __c15 <"/sys/module/vt/parameters/default_$__c"
-		__i=0
-		while [ "$__i" -le 15 ]
-		do
-			eval "__cl$__i=\"\${__cl$__i:-\$(_dec2hex \${__c$__i})}\${__cl$__i:+,\$(_dec2hex \${__c$__i})}\""
-			__i="$((__i + 1))"
-		done
-	done
-
-	__i=0
-	while [ "$__i" -le 15 ]
-	do
-		eval "echo COLOR_$__i=\"\${__cl$__i}\""
-		__i="$((__i + 1))"
-	done
-}
-
-## parse '$_ENV_FILE' into vtrgb
-_parse() {
-	local __i __j __c __rgb
-	local __r __g __b # read values
-	local __red __grn __blu # processed values
-	local IFS
-
-	if [ -f "$_ENV_FILE" ]
-	then . "$_ENV_FILE"
-	else echo "$_SELF: $_ENV_FILE: No such file" >&2
-	fi
-
-	COLOR_0="${COLOR_0:-00,00,00}"
-	COLOR_1="${COLOR_1:-aa,00,00}"
-	COLOR_2="${COLOR_2:-00,aa,00}"
-	COLOR_3="${COLOR_3:-aa,55,00}"
-	COLOR_4="${COLOR_4:-00,00,aa}"
-	COLOR_5="${COLOR_5:-aa,00,aa}"
-	COLOR_6="${COLOR_6:-00,aa,aa}"
-	COLOR_7="${COLOR_7:-aa,aa,aa}"
-	COLOR_8="${COLOR_8:-55,55,55}"
-	COLOR_9="${COLOR_9:-ff,55,55}"
-	COLOR_10="${COLOR_10:-55,ff,55}"
-	COLOR_11="${COLOR_11:-ff,ff,55}"
-	COLOR_12="${COLOR_12:-55,55,ff}"
-	COLOR_13="${COLOR_13:-ff,55,ff}"
-	COLOR_14="${COLOR_14:-55,ff,ff}"
-	COLOR_15="${COLOR_15:-ff,ff,ff}"
-
-	__i=0
-	while [ "$__i" -le 15 ]
-	do
-		eval "__rgb=\"\$COLOR_$__i\""
-		__j=0
-		IFS=','; for __c in $__rgb
-		do
-			[ "$__j" -eq 0 ] && __red="${__red:-$(_hex2dec "$__c")}${__red:+,$(_hex2dec "$__c")}"
-			[ "$__j" -eq 1 ] && __grn="${__grn:-$(_hex2dec "$__c")}${__grn:+,$(_hex2dec "$__c")}"
-			[ "$__j" -eq 2 ] && __blu="${__blu:-$(_hex2dec "$__c")}${__blu:+,$(_hex2dec "$__c")}"
-			__j="$((__j + 1))"
-		done; unset -v IFS
-		__i="$((__i + 1))"
-	done
-	printf "%s\n" "$__red" "$__grn" "$__blu"
-}
-
-## set the console colors
-## requires root privileges (for setvtrgb)
-## $1: target tty
-_set() {
-	local __target_tty="$1"
-	_parse | setvtrgb -C"$__target_tty" -
-}
-
-# DEPRECATED/REWRITE END
-#==============================================================================#
-
-
-# TODO: move opt parsing to main()
-# DEPRECATED: --env-file --help --usage
-main() { local mode="$1" target_tty="${2:-$(tty)}"
-	case "$mode" in
-		'' | get ) _get ;;
-		parse ) _parse ;;
-		set )
-			if ! _set "$target_tty" ; then
-				echo "$_SELF: requires root privileges" >&2
-				exit 4
+# get the configured and current colors
+# $1: ENVFILE
+function _get { local -r envfile="$1"
+	local var value file ; local -a colors
+	if [[ -f "$envfile" ]] ; then
+		while IFS='=' read -r var value ; do
+			if [[ "$var" == THEME ]] ; then
+				echo "SYSTEM: THEME=$value"
+			elif [[ "$var" == COLORS ]] ; then
+				echo "SYSTEM: COLORS=$value"
 			fi
-		;;
-		*)
-			echo "$_SELF: invalid mode of operation -- '$mode'" >&2
+		done < "$envfile"
+	else
+		echo "$_SELF: $envfile: No such file" >&2
+	fi
+	mapfile -t colors < <( getvtrgb | vtrgb2hex )
+	printf 'CURRENT: COLORS="%s"\n' "${colors[*]}"
+}
+
+# set the colors
+# $@: ENVFILE CONSOLE
+function _set { local -r envfile="$1" console="$2"
+	local var value file ; local -a colors
+	if [[ -f "$envfile" ]] ; then
+		while IFS='=' read -r var value ; do
+			if [[ "$var" == THEME ]] ; then
+				file="${value//\"/}"
+				if [[ -f "$file" ]] ; then
+					setvtrgb -C "$console" "$file"
+				else
+					echo "$_SELF: $file: No such file" >&2
+					return 1
+				fi
+				break
+			elif [[ "$var" == COLORS ]] ; then
+				printf '%s\n' ${value//\"/} | setvtrgb -C "$console" -
+				break
+			fi
+		done < "$envfile"
+	else
+		echo "$_SELF: $envfile: No such file" >&2
+		return 1
+	fi
+}
+
+# $@: [-C CONSOLE] [-E ENVFILE] [MODE (get)]
+function main {
+	local console envfile OPT OPTARG OPTIND
+	while getopts ':C:E:h' OPT ; do
+		case "$OPT" in
+			'C' ) console="$OPTARG" ;;
+			'E' ) envfile="$OPTARG" ;;
+			'h' ) _usage ;;
+			'?' )
+				echo "$_SELF: invalid option -- '$OPTARG'" >&2
+				_usage 2
+			;;
+			':' )
+				echo "$_SELF: missing argument -- '$OPTARG'" >&2
+				_usage 2
+			;;
+		esac
+	done ; shift "$(( OPTIND - 1 ))" ; mode="$1"
+	: ${mode:=get}
+	case "$mode" in
+		get ) _get "${envfile:-@ENVFILE@}" ;;
+		set ) _set "${envfile:-@ENVFILE@}" "${console:-@TTY@}" ;;
+		* )
+			echo "$_SELF: invalid mode -- '$mode'" >&2
 			_usage 2
 		;;
 	esac
-}
-
-# parse the options
-while true
-do
-	case "$1" in
-	-E|--env-file) _ENV_FILE="$2"; shift 2 ;;
-	-h|--help|--usage) _usage ;;
-	--) shift; break ;;
-	-*|--*) _usage 2 "$1" ;;
-	*) break ;;
-	esac
-done
-
-main "$@"
+} ; main "$@"
